#!/bin/bash

# Quantization
QU=1e4

rm -rvf barcelona
mkdir -p build barcelona

curl -o build/0301040100_BCN_Unitats_Adm.zip -C - 'https://raw.githubusercontent.com/martgnz/bcn-shp-zip/master/Unitats%20Administratives/Shp/0301040100_BCN_Unitats_Adm.ZIP'
unzip -jod build build/0301040100_BCN_Unitats_Adm.zip

geo2topo -n census_tracts=<( \
    shp2json build/0301040100_SecCens_ADM_ETRS89.shp \
      | geoproject 'd3.geoIdentity().reflectY(true).fitSize([960, 500], d)' \
      | ndjson-split 'd.features' \
      | ndjson-map '(d.id = d.properties.SEC_CENS, d)') \
  | topomerge aeb=census_tracts -k 'd.properties.AEB' \
  | topomerge neighborhoods=census_tracts -k 'd.properties.BARRI' \
  | topomerge big_neighborhoods=census_tracts -k 'd.properties.GRANBARRI' \
  | topomerge districts=neighborhoods -k 'd.properties.DISTRICTE' \
  | topomerge city=districts \
  > barcelona/census_tracts.json

# Inspired by: https://bl.ocks.org/mbostock/39b34968ad5eab65de1d7da81f78bb27
# Re-compute the topology as a further optimization.
# This consolidates unique sequences of arcs.
# https://github.com/topojson/topojson-simplify/issues/4
topo2geo -n \
  < barcelona/census_tracts.json \
  census_tracts=barcelona/_census_tracts.json \
  aeb=barcelona/_aeb.json \
  neighborhoods=barcelona/_neighborhoods.json \
  big_neighborhoods=barcelona/_big_neighborhoods.json \
  districts=barcelona/_districts.json \
  city=barcelona/_city.json

geo2topo -n \
  census_tracts=<( \
      cat barcelona/_census_tracts.json \
        | ndjson-map '(delete d.properties, d)') \
  aeb=<( \
      cat barcelona/_aeb.json \
        | ndjson-map '(delete d.properties, d)') \
  neighborhoods=<( \
      cat barcelona/_neighborhoods.json \
        | ndjson-map '(delete d.properties, d)') \
  big_neighborhoods=<( \
      cat barcelona/_big_neighborhoods.json \
        | ndjson-map '(delete d.properties, d)') \
  districts=<( \
      cat barcelona/_districts.json \
        | ndjson-map '(delete d.properties, d)') \
  city=<( \
      cat barcelona/_city.json \
        | ndjson-map '(delete d.properties, d)') \
  | topoquantize $QU \
  > barcelona/census_tracts.json

rm barcelona/_*.json
